const MessageTypes = {
  SKIP_WAITING: 'SKIP_WAITING',
  CLIENTS_CLAIM: 'CLIENTS_CLAIM',
  CACHE_UPDATED: 'CACHE_UPDATED',
  LO_QUE_SEA: 'LO_QUE_SEA',
  LOAD_PUSH_URL: 'LOAD_PUSH_URL'
}

export default MessageTypes
